services:
  - type: web
    name: tictactoe-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: PORT
        value: 10000
